Repository geo-classroom/python-mapfactory, pull requests merged in 2022-10, with the labels that each got.

#7 First commit - created a map in Folium
  Code.ipynb
  Code2.ipynb
Labels: hacktoberfest-accepted

#13 Boundary and point data
  Marinet/Map.ipynb
  Marinet/Points.ipynb
Labels: hacktoberfest-accepted, coding-level2

#33 Teaching someone pandas/matplotlib
  CREATE_CHOROPLETH_MAP.ipynb
  GMT_320_ASSIGNMENT_2.ipynb
  Hlamarisa/3.1-data-sheet-udemy-courses-web-development.csv
  Hlamarisa/Hlamarisa_Teaching_Someone_Pandas_and_Mathplotlib.ipynb
  Hlamarisa/exams.csv
  Hlamarisa_CREATE_CHOROPLETH_MAP.ipynb
Labels: hacktoberfest-accepted

#23 Task 1: Folium map
  Assignement2_task1.ipynb
  Assignment2_task2.ipynb
Labels: hacktoberfest-accepted

#32 Choropleth Map with 3 classes using Quantiles Scheme
  Ramoraswi/Choropleth_Map(3_classes_using_Quantiles).ipynb
Labels: hacktoberfest-accepted, coding-level1

#36 Function to create a proportional symbol map using a point layer.
  Hlamarisa/Capital_Cities.gpkg
  Hlamarisa/Capital_Cities.gpkg-shm
  Hlamarisa/Capital_Cities.gpkg-wal
  Hlamarisa/Hlamarisa_Proportional_Symbol.ipynb
  Hlamarisa/country_boundaries_v2.json
Labels: hacktoberfest-accepted, coding-level2

#35 Bin points to specific polygons
  Joyce_Assignment2/Task_Six.ipynb
Labels: hacktoberfest-accepted, coding-level2

#34 Function to create Choropleth map of 7 classes using population attribute
  Daniel/Daniel_Rielly_Choropleth_7_Classes/Daniel_Rielly_Choropleth_7_Classes.ipynb
Labels: coding-level1

#38 Choropleth map with5 classes, Quantile scheme
  Ramoraswi/Choropleth_Map_(5_classes_using_Quantiles).ipynb
Labels: hacktoberfest-accepted, coding-level1

#45 Pandas tutorial for beginners using California housing data
  Tsheamo/california_housing_train.csv
  Tsheamo/pandas_tut.ipynb
Labels: hacktoberfest-accepted, coding-level2

#46 Proportional symbol map
  Joyce_Assignment2/Task_Seven.ipynb
Labels: hacktoberfest-accepted, coding-level2
